### ISSUE TITLE
add leading dot

### ISSUE THREAD

**Issue by aeosynth** [simeji/jid#25]
instead of silently ignoring everything except the dot character, just start with it inserted, or don't require it at all

**Comment by simeji** [comment]
@aeosynth  I think so, too. I try to fix it.
I'll have this way.
> just start with it inserted

**Comment by simeji** [comment]
@aeosynth I implemented it  :) 
https://github.com/simeji/jid/commit/4358a76bfb674e4bd7f53a670628c6d0123d23ad
what do you think?

**Comment by aeosynth** [comment]
works, thanks. maybe make it not deletable?
