### ISSUE TITLE
Doesn't work with keys containing periods.

### ISSUE THREAD

**Issue by faulkner** [simeji/jid#32]
Autocomplete and selection break down when the keys contain periods.  Example use case:
```json
{
  "hosts": {
    "192.168.0.1": "a",
    "192.168.1.1": "b"
  }
}
```

**Comment by beta-phenylethylamine** [comment]
I had a similar issue trying to use it when the keys were urls

According to jq, the right way to select these would be with (with op's example) `.hosts.["192.168.0.1"]` but jid won't even let you type a `[` in that case

**Comment by simeji** [comment]
@faulkner @transitracer 
I've fixed this issue in https://github.com/simeji/jid/releases/tag/v0.7.6

**Comment by simeji** [comment]
If problems are caused, plz reipen this issue.
