### ISSUE TITLE
Support for less strict JSON

### ISSUE THREAD

**Issue by Rybadour** [simeji/jid#47]
Could we get support for JSON that isn't so strictly formatted:

```
{
  foo: "bar",
  // Comment for good measure
  baz: "foo",
}
```

In the wild JSON is going to appear like this a lot.

**Comment by simeji** [comment]
@Rybadour Thx for your proposal.
I don't feel like supporting strict JSON.
I think JSONs should be used in the right format.

**Comment by simeji** [comment]
If you had requests any more, please reopen this issue.
