### ISSUE TITLE
Add coloreful output like in jq

### ISSUE THREAD

**Issue by deniss-s** [simeji/jid#50]
Colorful output is really missing. 
This feature could be optional like in jq (`-C` colorize output, `-M` monochrome output). It's not vital, but would be a really nice to have.

**Comment by nwidger** [comment]
#43 is attempting to add colorized JSON to `jid`.

**Comment by simeji** [comment]
@deniss-s  
I got that feature's implementation. (colorize output & monochrome option)
https://github.com/simeji/jid/pull/51
