### ISSUE TITLE
Dot in keyname clashes with drilldown token

### ISSUE THREAD

**Issue by daniellowtw** [simeji/jid#54]
The drilldown token `.` can appear in the key name of the json object and will break drilling down

```
> echo '{ "a.a": 123 }' | jid

[Filter]> .
{    
  "a.a": 123
}

[Filter]> .a.a
 null

[Filter]> ."a.a"    
 null
```

The first prompt suggested the autocomplete `.a.a` which doesn't work.

**Comment by daveloyall** [comment]
Duplicate of #32.

**Comment by fiatjaf** [comment]
Shameless self-promotion: that feature is supported in https://github.com/fiatjaf/jiq, which is a fork of the amazing jid, but using the jq parser, such that complicated keys like "a.a" are supported like `.["a.a"]`.

**Comment by simeji** [comment]
@daniellowtw

I've fixed this issue in https://github.com/simeji/jid/releases/tag/v0.7.6

**Comment by simeji** [comment]
I

**Comment by simeji** [comment]
If you have any questions, plz open this issue again.

**Comment by simeji** [comment]
If you have any questions, plz open this issue again.
