### ISSUE TITLE
version string is old

### ISSUE THREAD

**Issue by ilovezfs** [simeji/jid#57]
To correct the version, I'm needing to do
```
    # Fix version
    inreplace "cmd/jid/jid.go", "VERSION = \"0.6.2\"",
                                "VERSION = \"#{version}\""
```
Is this something I should be passing via LDFLAGS or should it bumped in the code each time it's tagged? Thanks!

**Comment by simeji** [comment]
@ilovezfs Sorry, I fixed it at https://github.com/simeji/jid/pull/59 .
