### ISSUE TITLE
Does NOT work inside tmux

### ISSUE THREAD

**Issue by fogine** [simeji/jid#64]
Prints characters all over the place and shifts cursor when inside a tmux session (viz image)

![jid_tmux_bug](https://user-images.githubusercontent.com/7884288/37349351-820c78bc-26d6-11e8-9e43-09a800985abb.jpg)

When not inside tmux session, jid workds as expected in the same terminal.

![jid_tmux](https://user-images.githubusercontent.com/7884288/37349482-d423fdaa-26d6-11e8-8a5e-425dbed77b69.jpg)

**Comment by evs-ch** [comment]
Seems to be a `$TERM`-related-issue; with TERM screen-256color or xterm-256color I have that issue as well, if I run jid with `TERM=xterm jid < whatever.json`, for example, it works as expected.

**Comment by simeji** [comment]
@evs-ch thx!
I tried jid with tmux and it worked well.
My environment's $TERM is `xterm-256color`.
I think this issue is a tmux related issue, too.

**Comment by simeji** [comment]
@fogine If you don't resolve this issue even though you set $TERM (e.g. `xterm-color`), please reopen this issue.
