### ISSUE TITLE
Feature request: Scroll with key arrows and pageup-down

### ISSUE THREAD

**Issue by keymon** [simeji/jid#78]
Arrow up/down are not being used, why not map them to Ctrll+j/k. Same for page up/down

**Comment by simeji** [comment]
@keymon 
Have implemented PageUp/Down with Ctrl P/N.
https://github.com/simeji/jid/releases/tag/v0.7.5

**Comment by simeji** [comment]
If you had requests any more, please reopen this issue or create another one.
