### ISSUE TITLE
Loaded JSON file is one-line form inside jid

### ISSUE THREAD

**Issue by waldauf** [simeji/jid#88]
Hello,

I tried `jid` and this tool looks really great, thx for that. 
I have question about formatting. When I tried the example from readme I see all the time json in one-line format:
```
$ echo '{"aa":"2AA2","bb":{"aaa":[123,"cccc",[1,2]],"c":321}}' | jid
[Filter]> .
{"aa":"2AA2","bb":{"aaa":[123,"cccc",[1,2]],"c":321}}
```
I tried to use `python -m json.tool` but still the same result:
```
echo '{"aa":"2AA2","bb":{"aaa":[123,"cccc",[1,2]],"c":321}}'| python -m json.tool | jid
```

**Comment by 0xCAP** [comment]
Same here, using v0.7.6 with kitty v0.19.1 on Arch.

**Comment by waldauf** [comment]
I tried it again and now it works. JSON is properly formatted and colored. I didn't change anything. For me, this request can be closed.

**Comment by cben** [comment]
Same here.  Fedora 33, go1.15.13.  gnome-terminal, xterm, konsole — terminal doesn't seem to matter.

**Comment by cben** [comment]
Hmm, that was installing it by the one-liner `go get -u github.com/simeji/jid/cmd/jid`.
But a manual git clone and `go install ./cmd/jid/`, whether from master or any of v0.7.4 to v0.7.6, works fine — indented and multi-line. No idea what's the difference :shrug:
